### Assignment: 1.2 Exercise, working with Arrays 
### Name: Prashant Raghuwanshi 
### Date: 9/04/2021
### Course: DSC550-T301 Data Mining (2221-1)

In [1]:
import numpy as np

####  1) Create an array of size [10,50] and use the random function to fill it with integers between 1 and 500 (inclusive). Load it to a DataFrame.

In [2]:
array_randnums= np.random.randint(1,501, size=(10,50))
array_randnums

array([[120,  80, 309, 488, 146, 159, 210, 305, 333, 190, 360, 472, 164,
        298, 340, 362, 240,  29, 292,  70, 102, 340, 299, 163, 279, 213,
        318, 405, 441, 337, 140, 313,  12, 241, 216, 384, 477, 440, 303,
        384,  45, 335,  91, 127,  61, 452, 262, 363, 209, 412],
       [347, 159, 413, 492, 435, 293, 348, 177, 371, 237, 402,  33, 206,
        268, 105,  68,  18, 274, 483, 171,  16, 120, 249, 479, 447, 212,
        238, 302,  67, 280, 498, 310, 466,  17,  34, 370,  98, 314, 224,
        126,  94, 231, 449, 102,  37, 384, 282,  66, 365, 132],
       [288, 105, 231,  19, 381, 420, 222, 136, 256, 117, 253, 358, 154,
        352, 343, 297,  27, 213, 123, 371, 153, 408,  94, 260, 141, 336,
         31,  34,  77,   3, 275, 128, 458, 448,  92,  70, 295, 309, 114,
        439, 181, 138, 399, 174, 209, 193, 448, 113, 328, 175],
       [254, 436,  39, 360,  10, 457, 203, 199,  75, 467, 405, 233, 206,
        488, 383, 402, 270, 175, 340,  85, 332, 113,  78, 318, 310, 334,
     

#### 2) Calculate the sum of each row; the sum of each column; and the sum of all entries.


In [3]:
sumofeachrow = np.sum(array_randnums,axis=1).tolist()
sumofeachrow

[13131, 12309, 11189, 13971, 14727, 13512, 11704, 11770, 14346, 12052]

In [4]:
sumofeachcolumn = np.sum(array_randnums,axis=0).tolist()
sumofeachcolumn

[2439,
 2355,
 2462,
 2852,
 2865,
 2426,
 2393,
 2951,
 3172,
 3146,
 3005,
 2511,
 2363,
 2748,
 2856,
 2469,
 2380,
 2635,
 2716,
 3038,
 1969,
 2064,
 2524,
 2495,
 2447,
 2538,
 1681,
 3022,
 2515,
 1900,
 2588,
 2717,
 2313,
 2688,
 1871,
 3023,
 3091,
 3077,
 2505,
 2803,
 1939,
 2211,
 2793,
 1606,
 3143,
 3055,
 2475,
 2522,
 2488,
 2866]

#### 3) Determine the minimum; maximum; average; and standard deviation of all entries.

In [5]:
minimum = np.min(array_randnums)
maximum = np.max(array_randnums)
mean = np.mean(array_randnums)
standarddeviation = np.std(array_randnums)

In [6]:
minimum, maximum, mean, standarddeviation

(1, 500, 257.422, 140.7367326464559)

#### 4) Sort the DataFrame: 
##### a) sort on column 2
##### b) sort on row 2.

In [7]:
sortoncolumns = array_randnums[array_randnums[:, 1].argsort()]
sortoncolumns

array([[120,  80, 309, 488, 146, 159, 210, 305, 333, 190, 360, 472, 164,
        298, 340, 362, 240,  29, 292,  70, 102, 340, 299, 163, 279, 213,
        318, 405, 441, 337, 140, 313,  12, 241, 216, 384, 477, 440, 303,
        384,  45, 335,  91, 127,  61, 452, 262, 363, 209, 412],
       [288, 105, 231,  19, 381, 420, 222, 136, 256, 117, 253, 358, 154,
        352, 343, 297,  27, 213, 123, 371, 153, 408,  94, 260, 141, 336,
         31,  34,  77,   3, 275, 128, 458, 448,  92,  70, 295, 309, 114,
        439, 181, 138, 399, 174, 209, 193, 448, 113, 328, 175],
       [ 31, 142, 271, 209, 233, 203,  26,  85, 109, 316,   2, 349, 328,
        212, 196, 261,  80, 290,  93, 474, 214, 227, 317, 110,  51, 456,
        107, 246, 333, 378, 171, 422,  29, 165, 332, 157, 460, 289,  25,
        346, 195, 390,  55, 308, 439, 227, 144, 368, 497, 336],
       [ 43, 151, 404, 331, 379,  49, 343, 446, 269, 443, 103, 224, 466,
        137, 299, 500, 424, 483, 483, 352, 270, 218, 169,  51, 422, 311,
     

In [8]:
sortonrow = array_randnums[:, array_randnums[1, :].argsort()]
sortonrow

array([[102, 241, 240, 472, 216,  61, 363, 441, 362,  45, 477, 127, 340,
        340, 384, 412,  80,  70, 305, 164, 213, 303, 335, 190, 318, 299,
        298,  29, 337, 262, 159, 405, 313, 440, 120, 210, 209, 384, 333,
        452, 360, 309, 146, 279,  91,  12, 163, 292, 488, 140],
       [ 16,  17,  18,  33,  34,  37,  66,  67,  68,  94,  98, 102, 105,
        120, 126, 132, 159, 171, 177, 206, 212, 224, 231, 237, 238, 249,
        268, 274, 280, 282, 293, 302, 310, 314, 347, 348, 365, 370, 371,
        384, 402, 413, 435, 447, 449, 466, 479, 483, 492, 498],
       [153, 448,  27, 358,  92, 209, 113,  77, 297, 181, 295, 174, 343,
        408, 439, 175, 105, 371, 136, 154, 336, 114, 138, 117,  31,  94,
        352, 213,   3, 448, 420,  34, 128, 309, 288, 222, 328,  70, 256,
        193, 253, 231, 381, 141, 399, 458, 260, 123,  19, 275],
       [332, 154, 270, 233,  74, 481, 339, 284, 402, 496, 242,  55, 383,
        113, 378, 451, 436,  85, 199, 206, 334, 269, 230, 467, 430,  78,
     